jobs:
  - job: DockerBuild
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'docker hub'
          repository: 'amond/azure-docker-agent'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
